### PR TITLE
Fixing DATA_CUSTOMIZE hass 2024.11 issue

### PR DESCRIPTION
**Pull request by gsaurer**
Fixing the issue that component is not loading with hass 2024.11

### CODE REVIEW

**Comment by jaym25** [comment]
@gsaurer - It appears that the following line by itself works for versions 2024.11 and below:

> from homeassistant.helpers.entity import DATA_CUSTOMIZE

Would you like to check that out for yourself and update your pull request?

**Comment by lukas-hetzenecker** [comment]
Thanks for the bugfix @gsaurer , released a new version

**Comment by lukas-hetzenecker** [comment]
@jaym25 quickly released a bugfix there, wanted to prevent more issues being opened and more users being affected now that the new stable homeassistant got released (any my instance was also affected by it 😅)

**Comment by jaym25** [comment]
@lukas-hetzenecker  Sounds good. :-)

**Pull request merged**
